site_name: Perovksite tandem documentation
site_author: T. Jesper Jacobsson
theme:
  name: material
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
  features:
    # - navigation.expand
    - navigation.sections
    - navigation.tracking
    - navigation.path

plugins:
  - search
  - macros
  - include-markdown

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true


nav:
  - Reference data: reference_data.md
  - General: general/general.md
  - key performance metrics: key_performance_metrics.md
  - Module_data: module/module_data.md  
  - Measurements: 
    - JV_measurements: measurements/JV.md
    - EQE_measurements: measurements/EQE.md
    - Stabilized_performance: measurements/Stabilized_performance.md
    - Stability: measurements/Stability.md
    - Outdoor_performance: measurements/Outdoor_performance.md
    - Transmission: measurements/Transmission.md
    - Flexibility: measurements/Flexibility.md
  - Device_stack: 
    - Summary: device_stack/device_stack_general.md
    - Layers: device_stack/layers.md
  - Experimental_procedures: experimental_procedures/experimental_procedures.md
  - Encapsulation: encapsulation/encapsulation_data.md                                         
